### ISSUE TITLE
picture chaning issue 

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#45]
picture changing for the products already sent prodcuts details in whatsapp

**Comment by ZateLabClients** [comment]
I requested many times to add the detailes here, including product id, 
From 100s of whatsapp audios how can i find the the issue audio.

**Comment by ZateLabClients** [comment]
I investigated the problem. The problem was with the data entering via excel.
U accidentally changed product_id of "One Piece Portrait of Pirates". 
Always use excel file carefully.
Main steps to remember.
1. if product_id 54 is misisng in excel, do not try to add it
2. always use new product_id for new products
